name: FidoDemo
options:
  bundleIdPrefix: com.fidodemo
  deploymentTarget:
    iOS: "16.0"
settings:
  DEVELOPMENT_TEAM: ""
  PRODUCT_BUNDLE_IDENTIFIER: com.fidodemo.FidoDemo
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.0"
  INFOPLIST_FILE: FidoDemo/Info.plist
  CODE_SIGN_STYLE: Automatic
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  TARGETED_DEVICE_FAMILY: "1,2"
targets:
  FidoDemo:
    type: application
    platform: iOS
    sources:
      - path: FidoDemo
        excludes:
          - "Info.plist"
    info:
      path: FidoDemo/Info.plist
      properties:
        NSFaceIDUsageDescription: "Use Face ID to log in quickly and securely."
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
